export default function Contact() {
    return (
      <section id="contact" className="min-h-screen flex items-center justify-center">
        <h1 className="text-4xl">Contact</h1>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maiores doloribus consequatur, quisquam rem eligendi consectetur dignissimos eveniet iste! A quisquam ut, ex dolorum exercitationem fuga est dolor sunt atque libero?<br />
        Fugit blanditiis temporibus maiores architecto reprehenderit deserunt assumenda repudiandae hic, aut, nisi magnam neque culpa adipisci amet a inventore et officiis aperiam corrupti fugiat quasi, maxime est quibusdam? Non, saepe.<br />
        Itaque placeat quibusdam minus doloremque ea veniam est enim repudiandae. Quam, molestiae vitae? Nam id ipsam eligendi deserunt, architecto perspiciatis est sapiente cum. Debitis quo atque ut quibusdam adipisci cupiditate.<br />
        Repellat iste eveniet nulla, voluptas, unde animi amet enim a at neque quidem modi quae et, maiores cupiditate accusamus vel ea quod! Iste hic inventore incidunt doloribus totam, repellat dicta.<br />
        Porro ut provident tenetur quod! Aliquid, assumenda tempora cum exercitationem dolore eum similique dolorum tenetur dicta tempore quia? Veniam magni labore consequuntur officiis nam soluta ex culpa tempore, quia earum.<br />
        Animi eum odio id distinctio quos, quia, neque iste modi dolores unde corrupti. Quae rem quis esse magni vero consectetur molestias fuga excepturi, repudiandae tenetur officia impedit, odit reiciendis delectus.<br />
        Aut, doloribus cumque quia hic atque natus similique vitae molestias dicta facilis. Omnis porro nihil amet quasi a iusto. Nostrum repudiandae tempora omnis ad quo nulla optio illo repellendus voluptates!<br />
        Atque perferendis ea laborum, consectetur blanditiis deserunt quae vitae, a beatae rerum dolores iste aliquid consequuntur exercitationem at temporibus alias, sequi dolorem neque delectus nisi facere culpa adipisci pariatur? Voluptas!<br />
        Praesentium quibusdam, fugit veniam nam impedit saepe ea id vel nisi explicabo, omnis ipsum qui. Modi mollitia ipsum numquam sed accusantium repellat vel odio voluptatum quidem, expedita enim, nemo dolorem!<br />
        Expedita rerum dignissimos facere nam illo quos repellendus error saepe minus harum aliquam officia voluptatibus earum ex, maiores dolorum iusto amet aut hic voluptatum sunt nulla! Et rerum excepturi dolore.<br />
        Dolore voluptas voluptate neque atque minima mollitia iste enim id quidem, earum veritatis illum odio, inventore perferendis quasi, autem eveniet expedita laudantium? Adipisci obcaecati illum facere magnam, quisquam totam recusandae!<br />
        Numquam nihil rerum voluptatum quia dolor, incidunt neque totam eum culpa perferendis laborum distinctio in necessitatibus voluptatibus porro explicabo accusamus autem facere alias pariatur iure optio dolorem velit nisi! Veritatis.<br />
        Earum officiis nisi dolorem alias, ea mollitia iure deleniti dignissimos ab, libero neque veniam dicta, ullam suscipit voluptatibus culpa sit praesentium laboriosam amet voluptates saepe! Repudiandae harum enim sunt veniam!<br />
        Facilis voluptates distinctio id blanditiis provident corporis, reiciendis corrupti fugiat consectetur. Sint modi debitis odio, consectetur obcaecati quibusdam maxime dignissimos excepturi aspernatur quod ex culpa deserunt nam delectus perspiciatis commodi.<br />
        Laboriosam perspiciatis laborum, sunt in voluptatum nesciunt quos sit dicta consectetur laudantium, hic deserunt aut cupiditate dolores ducimus, ipsam molestias vero assumenda ad dolorum veritatis enim maiores? Ad, suscipit sapiente.<br />
        Labore delectus qui aliquam in dolores! Dicta aliquid ullam accusamus ut neque, placeat iure iste ducimus quod repellendus omnis eaque animi amet facilis. Tenetur beatae magnam corporis nostrum unde corrupti.<br />
        Suscipit corrupti numquam, commodi nisi temporibus perferendis unde vero hic sapiente? Alias, natus! Ipsum quisquam odit provident sequi quia nobis. Beatae debitis deserunt ullam! Magnam adipisci omnis enim atque delectus.<br />
        Quisquam modi eligendi recusandae incidunt labore aliquam veritatis. Enim culpa ipsa corrupti eaque dolorum a magnam aperiam ut at id dolorem iste inventore hic nesciunt, nam nobis quisquam ducimus? Iste?<br />
        Ad nam dolorum, earum reprehenderit esse error laudantium doloribus quisquam amet aut accusamus numquam ullam aliquam odit repellendus, possimus magnam voluptatum, blanditiis quibusdam atque facilis. Eligendi, id vel. Amet, odit.<br />
        Fugiat cupiditate iusto fuga culpa voluptas iste facere corrupti? Atque cum quisquam perspiciatis perferendis ipsum veritatis quia iusto, quidem dolorum ad odit officiis recusandae iure pariatur repellendus voluptatum nulla quas.<br />
        Et consectetur a nostrum. Nemo exercitationem saepe voluptatibus molestias. Dolorum, laborum aliquid magni doloremque hic nihil distinctio, temporibus assumenda tenetur delectus cumque, consectetur harum! Tempore neque ea repudiandae quibusdam enim.<br />
        Quasi quis nemo voluptas deserunt, nam ratione modi vitae adipisci laboriosam qui officia impedit beatae rerum omnis delectus, dolores repellat provident velit iusto voluptatem corporis illo corrupti. Odit, ducimus molestiae.<br />
        Aliquid numquam ut nesciunt ea ad tempora fuga placeat voluptas minus ex culpa ullam assumenda possimus quisquam, sed molestias praesentium consectetur debitis, tempore rem, tenetur aperiam. Provident dolores nesciunt harum.<br />
        Tempore asperiores, doloribus qui in ex voluptatum, voluptatibus ratione iste autem natus labore eligendi et itaque. Facere similique iusto natus autem vitae. Iusto maxime velit molestiae? Aspernatur ullam sunt quos.<br />
        Earum iste ad rerum, quo magni fuga suscipit, nemo totam harum maiores quod recusandae deleniti unde. Eum, reprehenderit nostrum! Quasi, iure doloremque? A magnam deleniti, fuga excepturi ratione maiores impedit?<br />
        Soluta laudantium enim unde amet ipsa odio. Deleniti, hic autem illo dignissimos esse sapiente omnis ratione sint iusto blanditiis repellendus ipsam harum culpa cupiditate sed! Nesciunt natus fugit velit soluta!<br />
        Error cumque quis ad quam dolorum earum, officiis, vero voluptatibus, quidem repudiandae veniam praesentium id. Quis enim, mollitia, exercitationem quisquam recusandae tempore quae itaque, debitis numquam possimus beatae deleniti incidunt.<br />
        Eos nemo reiciendis ducimus deleniti hic est voluptatum odio perspiciatis, nisi mollitia explicabo corrupti deserunt qui facere quos officiis maxime quod ullam repudiandae itaque doloribus ad minus? Id, nam voluptatem.<br />
        Ea tenetur consequuntur placeat dolorem numquam? Dolore pariatur quasi odio nostrum numquam! Aperiam, eius ad officia tempore fuga dolore placeat magnam repellendus distinctio accusamus a non repudiandae qui modi voluptas!<br />
        Laboriosam veniam est tempora eveniet vitae porro saepe nam nihil repudiandae sapiente aliquid, ipsum suscipit similique autem. Ut corporis dolores perferendis dolorum cumque vel neque assumenda quia voluptas! Officia, earum.<br />
        Dolor dolorum aliquam, explicabo quasi repudiandae, ratione maiores voluptatibus nesciunt facilis, ipsam facere dicta sit maxime temporibus cum tempore placeat? Dignissimos voluptate impedit esse facere necessitatibus doloremque aliquam vel quidem?<br />
        Nam aperiam hic quibusdam? Dolores totam voluptatum officia aliquid illum fugiat cum minus recusandae blanditiis atque porro, quas nesciunt magnam facilis architecto esse ad dignissimos iure cupiditate inventore. Doloribus, ex!<br />
        Veritatis hic voluptate voluptatem enim temporibus minima, dolorum a exercitationem eligendi est porro iure! Magni vel ipsam consequatur natus earum autem eveniet quas dolor quidem aperiam? Iusto eligendi magni ex?<br />
        Ipsam nobis magnam beatae impedit quos consectetur magni, adipisci voluptatibus culpa aspernatur modi asperiores odit perspiciatis saepe officiis fugit laudantium nam dolorem sapiente ullam! Qui accusantium odio explicabo facilis praesentium?<br />
        Recusandae quos et doloribus impedit voluptates. Ratione, id iste consequuntur ad aperiam corporis cum eligendi molestias est similique eveniet, quidem deserunt velit ullam sapiente tenetur praesentium perferendis, laborum inventore ut.<br />
        Incidunt cumque, minus qui suscipit consequuntur hic illum tempore voluptate delectus. Esse reprehenderit nemo repellat, facilis ratione vel exercitationem perspiciatis libero beatae provident quidem consequuntur, labore adipisci doloremque, iure officia?<br />
        Autem, ipsa ullam pariatur officia blanditiis nulla, nisi, necessitatibus est dolore laboriosam rem quibusdam quidem sequi! Excepturi, provident in est maxime ipsam unde praesentium, debitis commodi odit vero sit similique.<br />
        Quaerat, labore. Nesciunt dignissimos totam quo corporis vel dolores, eius distinctio unde, rem reiciendis ipsum nulla consequuntur nisi officiis facere mollitia ea architecto molestiae? Id optio aliquam eius ratione consequatur.<br />
        Atque aperiam hic nobis iusto dicta, quas tempore nesciunt perspiciatis reiciendis, libero eaque fuga pariatur? Aliquam inventore quisquam, pariatur sapiente rem optio enim ducimus quis in ipsa ab doloribus unde!<br />
        Modi reiciendis ratione dolore et labore alias suscipit quis cum? Itaque corporis nobis, voluptatibus quidem harum ducimus suscipit quis ex. Atque distinctio pariatur nostrum quis, possimus animi deleniti itaque unde.<br />
        Rerum sint veniam sed perferendis fugit quidem ea earum magni reiciendis iusto nobis, tempora suscipit obcaecati nisi voluptatum dicta excepturi! Reprehenderit adipisci consectetur neque eius culpa eos tempora aliquid eaque!<br />
        Ratione eveniet possimus quaerat fugiat est aperiam provident. Suscipit alias explicabo iste, repellat doloremque eum, commodi fugiat nostrum et fuga officia assumenda autem eius reprehenderit non soluta. Provident, minima harum!<br />
        Expedita facilis, atque hic dolorum ullam quasi omnis rerum esse, numquam dignissimos dolore delectus consequatur soluta nulla cupiditate aliquid consectetur eius ducimus natus at culpa. Aperiam facere molestiae autem. Sed!<br />
        Earum provident tempora delectus deleniti exercitationem unde atque ex et veritatis eius adipisci sunt aut eveniet voluptatibus ab necessitatibus velit, fugit omnis. Deleniti nisi in nam soluta laborum dolore officia!<br />
        Ullam, iste dicta dolores veritatis sint quas unde neque obcaecati molestias sit soluta vitae blanditiis quod consectetur aut dolor. Et, culpa? Provident eaque laboriosam magnam officia ullam adipisci culpa porro.<br />
        Eveniet asperiores, dolor nostrum velit, ducimus esse quas libero cumque autem, molestias corporis? Consequuntur veniam, vel neque recusandae veritatis saepe, nesciunt beatae corrupti eos quasi quia nulla ullam ratione asperiores?<br />
        Neque eveniet voluptas, soluta vitae harum amet accusamus facilis porro commodi doloremque fugit est aut quos error quaerat sed non, itaque accusantium vel adipisci eos autem natus? Nemo, inventore sed?<br />
        Veritatis accusamus nemo vitae cum, consequuntur pariatur, laborum officiis quis sint adipisci inventore ad iure, nihil ex numquam ducimus. Commodi voluptatibus quam maxime dolor deleniti labore minima voluptas sit dignissimos!<br />
        Magnam, eaque assumenda. Dolorem id dolor ea, nihil nulla officiis. Sapiente ab beatae natus eaque distinctio delectus iste. Praesentium exercitationem vitae esse, molestias cumque sint. Voluptatibus, culpa ratione! Magni, asperiores.<br />
        Nulla qui ipsum harum? Vitae qui eos sed aut, nesciunt nam. Vel obcaecati quam iste ea in quibusdam doloremque similique enim rerum quisquam? Id perferendis itaque aspernatur pariatur delectus in!<br />
        </p>
      </section>
    );
  }
  