export default function Projects() {
    return (
      <section id="projects" className="min-h-screen flex items-center justify-center">
        <h1 className="text-4xl">Projects</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima praesentium consequuntur earum iure, eius est ipsam eos, corrupti magnam rerum temporibus? Sed porro recusandae dolore earum accusamus optio inventore saepe.<br />
        Illum, cumque accusamus ipsum, laborum nesciunt veritatis totam perspiciatis sequi illo atque facilis soluta rem impedit nostrum, unde ex aliquam quam eum! Quae enim odio architecto molestiae qui, delectus placeat.<br />
        Quod pariatur, exercitationem error eaque nesciunt, tenetur voluptatem deserunt laboriosam asperiores cumque quo! At, sit consequatur commodi aliquam possimus, officiis odit quibusdam nisi ipsam, nostrum quae deserunt sequi necessitatibus optio.<br />
        Temporibus minima error quis blanditiis possimus nemo, repellendus officiis vitae accusamus adipisci at, molestias fugiat quaerat totam. A quia culpa velit ipsum ad consequuntur saepe. Sint itaque blanditiis quidem unde?<br />
        Eaque reprehenderit repellendus voluptatum, ducimus ea pariatur sunt? Voluptatem iusto provident praesentium pariatur corrupti perspiciatis iure commodi rerum. Iure odit ipsa pariatur tenetur iusto nobis in deserunt quidem magnam assumenda!<br />
        Non officia nisi consequuntur dolorem molestias, officiis repellat tempora. Aperiam consequatur sint maxime ipsa, labore placeat amet, iure veritatis fugit similique praesentium nam. Quae est et modi incidunt ut voluptas!<br />
        Suscipit accusantium atque expedita nostrum! Quos nam unde recusandae ducimus, vero explicabo perspiciatis soluta inventore? Illo illum officia quaerat quisquam totam quae odio voluptates recusandae reiciendis, excepturi debitis et nesciunt!<br />
        Quod illo fugit quibusdam aperiam perspiciatis facere, dolorum esse tempora ullam temporibus, distinctio numquam nemo commodi recusandae, impedit odit. Consectetur repudiandae saepe veritatis illo laudantium minus dignissimos, sint architecto tenetur.<br />
        Excepturi incidunt beatae obcaecati consequuntur itaque placeat ipsam quaerat reiciendis ducimus? Eum nemo fuga doloremque nesciunt quasi at, repudiandae tempora asperiores magnam sequi aperiam eveniet qui rem aliquid aliquam distinctio!<br />
        Excepturi nulla laborum laboriosam, temporibus enim corporis earum suscipit dicta eligendi, provident, molestias natus? Asperiores qui nostrum quasi recusandae, iusto amet explicabo. Corporis quae consectetur natus impedit quis. Obcaecati, praesentium?<br />
        Alias, perspiciatis tenetur! Illum fugiat sed odio quo error beatae culpa, enim magnam nisi tempore minus assumenda provident nam eveniet adipisci. Commodi magnam expedita praesentium, facilis ducimus mollitia laboriosam dolorum?<br />
        Culpa et cupiditate doloribus sapiente aut incidunt temporibus sit eius unde facere earum sed, architecto perspiciatis enim ab veniam in. Ducimus distinctio expedita numquam culpa itaque consequuntur sunt quae ratione.<br />
        Libero magnam fugit quasi laudantium, quas suscipit praesentium distinctio dolores id illo quisquam blanditiis omnis odit corporis cumque perferendis iure possimus! Officia, tenetur minus. Reprehenderit veniam aut officiis voluptas distinctio.<br />
        Voluptate culpa sequi cum commodi iste molestias reiciendis eos illo esse optio, provident vero, possimus excepturi corrupti? Quas, excepturi dolorem cum sed, dolores placeat quis, enim ipsa animi consequuntur suscipit.<br />
        Consequatur inventore voluptates ex molestiae dignissimos perferendis reiciendis et asperiores ad, iure magnam libero, iste deserunt eum in illo, praesentium ipsum odit id laboriosam. Distinctio itaque molestias doloremque labore neque.<br />
        Itaque, autem, esse obcaecati perspiciatis qui in fugit necessitatibus, voluptatibus adipisci eum dolor sed accusantium quos natus laboriosam totam reiciendis asperiores aspernatur corporis similique omnis labore saepe. Ducimus, alias iure.<br />
        Vel commodi quam animi et alias esse, quo distinctio. Dolore dolores unde cum vel? Expedita obcaecati perferendis exercitationem, asperiores aliquam facilis? Soluta quae earum illo cum ut. Ut, labore ipsam!<br />
        Eum neque consectetur molestias dolor illo officiis magni officia quasi corporis deserunt. Perspiciatis tenetur reiciendis ipsum eaque quaerat quis exercitationem odio asperiores? Temporibus laborum ipsum, unde quos voluptate tempore obcaecati.<br />
        Doloribus illo est officiis totam nostrum quaerat maxime alias expedita dignissimos cupiditate. Maiores iusto, sapiente et ea corporis debitis similique deleniti facilis eos illum sed fuga, quae aperiam. Dicta, voluptates.<br />
        Neque, eligendi natus. Fugiat quo unde fuga, asperiores quae illo corporis voluptatum illum, odit quis quam sed aspernatur? Cupiditate esse modi vitae impedit consequuntur itaque architecto repellat, incidunt officiis ad!<br />
        Commodi deserunt soluta vero assumenda veritatis velit pariatur adipisci, fuga voluptatem recusandae optio totam minus. Aut aperiam dicta nulla maxime minima molestiae quia, officia ducimus, laboriosam debitis fugiat ipsum voluptas.<br />
        Id, fuga tenetur! Earum dolore alias omnis possimus placeat. Ab hic eos aspernatur eaque eum, autem blanditiis quas odio doloremque facilis at temporibus totam. Fuga est exercitationem nulla nobis reiciendis?<br />
        Voluptatem culpa repudiandae vel temporibus esse tenetur facere praesentium illum eveniet. Excepturi unde animi ratione dolore libero inventore praesentium. Facere nihil exercitationem harum pariatur voluptatem culpa fuga suscipit. Numquam, quae.<br />
        Illo, harum? Ipsum modi, illum harum vitae quasi eum eius rem incidunt similique minima adipisci praesentium. Accusantium, velit optio. Temporibus quo accusantium dicta fugiat laudantium dolores quae pariatur, excepturi eum?<br />
        Omnis cum impedit mollitia expedita. Accusamus omnis, veniam officiis ex assumenda, praesentium magnam debitis numquam at magni neque excepturi repellendus animi consectetur repudiandae enim amet ratione, harum inventore eum molestias.<br />
        Quas debitis consequuntur aperiam dolor accusantium ipsum, quidem dolores aspernatur excepturi quos culpa repellat unde iusto laborum tempore aliquid recusandae blanditiis quaerat obcaecati qui! Eum blanditiis voluptates optio ducimus sed.<br />
        Sequi alias saepe odit quas error impedit, fugit eveniet molestias veniam vero neque, natus qui recusandae quidem esse tenetur deserunt asperiores at voluptatum consequuntur quam. Ipsa quae vitae iusto delectus.<br />
        Voluptas eum alias odit, recusandae quisquam autem ipsa incidunt dolorem repudiandae assumenda labore laudantium aut minima sunt eos accusantium sapiente ea veniam delectus. Quo odit sit enim fuga porro. Quibusdam.<br />
        Unde, dolore molestiae! Dolores, pariatur? Expedita ratione recusandae illum. Voluptatum corrupti quam, voluptatem totam sapiente velit esse excepturi aperiam molestiae vero magni accusamus. Delectus repellendus sint esse, voluptates facilis ad.<br />
        Reiciendis, unde error eius totam temporibus quas magnam nemo facere voluptatem sunt ab eos quidem eaque ad distinctio. Deleniti sed, voluptatibus odio sunt recusandae dolore cupiditate modi id repellat autem?<br />
        Quia nesciunt veritatis dolore optio ad officiis natus fugit iste consequatur iure quas totam quaerat, pariatur id consectetur. Sint iusto et blanditiis adipisci numquam fugiat libero possimus incidunt, sed illum.<br />
        Quas, molestias! Dolorem ipsa quam fugit repudiandae rem ipsum sed asperiores, debitis quisquam nostrum officia perspiciatis harum impedit possimus vero voluptates aspernatur laborum pariatur! Fuga provident nostrum distinctio iste neque?<br />
        Fugit, rem, explicabo maxime dolores a ullam necessitatibus est repellat repellendus, odit sed saepe quibusdam. Laborum odit ullam doloremque minus id, eveniet sit quia corrupti esse ipsum cupiditate enim illum.<br />
        Nesciunt dolore possimus sapiente, id rerum corrupti quod voluptas quam autem voluptate sunt praesentium debitis unde vel ipsa ad neque. Voluptates, voluptate in? Error, magnam deleniti laudantium explicabo nobis doloribus.<br />
        Accusamus, assumenda dignissimos! Temporibus atque enim nemo facere hic adipisci. Non fugiat quis repellendus hic numquam fugit enim quasi maiores, quidem rerum eaque itaque dolorem dolores odit consectetur. Repellat, architecto!<br />
        Rem in suscipit deserunt odit dolor eaque nobis, quibusdam aspernatur impedit voluptatem sit cumque corrupti nihil, animi tempora harum dolorem quasi commodi quis optio nulla? Accusamus quasi perspiciatis maiores placeat.<br />
        Quo quas pariatur aliquam impedit asperiores. Sed dignissimos voluptatibus quasi velit eveniet fugit, aliquid quo, atque non impedit nostrum pariatur, eaque in! Quaerat nesciunt praesentium alias ad officia laboriosam sequi.<br />
        Dicta tempore, omnis reiciendis quia eius laudantium aliquid perspiciatis numquam, repudiandae ipsa exercitationem reprehenderit expedita deleniti esse ipsum porro dignissimos eveniet sunt architecto. Molestias rem ab, enim reprehenderit asperiores sit.<br />
        Ea nobis sunt quia minus veniam. Sit corrupti numquam maxime, velit modi quae quibusdam quisquam ipsum, neque aperiam nihil dolore laudantium optio itaque in sint eum, fugiat eligendi eius fuga!<br />
        Id aliquid fuga nesciunt voluptatibus repudiandae minus molestias quis. Enim nesciunt dignissimos vel, facilis itaque quasi eos debitis sequi a nam quis aspernatur harum assumenda recusandae excepturi. Sint, ullam perferendis.<br />
        Molestias adipisci ratione corporis eum labore cupiditate repellendus fuga, aliquid suscipit voluptate nulla quibusdam odio sunt! Enim quibusdam id aut necessitatibus nisi saepe in officia repellat inventore aliquid! Architecto, totam.<br />
        Vel ullam, a fuga quas sint nostrum deleniti deserunt, dicta ratione dignissimos blanditiis laborum corrupti beatae earum sit velit saepe tempora, eos odio voluptatibus alias nesciunt laudantium. Voluptatum, facere dolor.<br />
        Eaque beatae natus quasi pariatur quia, voluptatibus, suscipit ipsum animi aperiam est odio! Aperiam voluptatum quasi voluptas voluptatibus, obcaecati temporibus, eos nobis expedita fugit odio consequuntur vitae a odit quia!<br />
        Laboriosam dicta voluptatum atque vel maiores quibusdam illo laudantium eaque, quas natus nostrum numquam distinctio reiciendis, ab amet similique aliquam obcaecati quos accusamus magnam molestiae alias impedit, quae hic. Facilis!<br />
        Adipisci odio qui magni eius, officia quibusdam beatae vel cum sapiente molestiae ipsa rem, minus sit a recusandae dignissimos voluptatum. Nostrum mollitia laudantium, aliquam dolorem dolor neque aperiam amet. Ullam.<br /></p>
      </section>
    );
  }
  